title: Ankit Wahane
logo: assets/ankit_wahane.jpg
description: # text below image
  As a Data Scientist with over 4 years of experience, I specialize in end-to-end machine learning solutions, including model development and deployment. Currently, I am focused on Generative AI (GenAI) projects.
  <br><br>
  <a href="https://www.linkedin.com/in/ankit-wahane/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="assets/Ankit_Wahane_Resume_2024_v1.3.pdf" target="_blank">View My Resume</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
